build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: projectweekend
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: projectweekend/drone-fabric
    when:
      branch: master

plugin:
  name: Fabric
  desc: Execute fabric commands for deployment
  type: deploy
  image: projectweekend/drone-fabric
  labels:
    - deployment
    - fabric
